version: '3.9'
services:
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: scrapy
      POSTGRES_PASSWORD: scrapy
      POSTGRES_DB: scrapy_db
    ports:
      - '60438:5432'

