"""migration_auto

Revision ID: rev20250903T201912
Revises: 
Create Date: 2025-09-03 23:19:13.036675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'rev20250903T201912'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Enum('YOUTUBE', 'INSTAGRAM', 'TELEGRAM', name='source'), nullable=False),
    sa.Column('channel_name', sa.String(), server_default='', nullable=False),
    sa.Column('created_channel_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), server_default='', nullable=False),
    sa.Column('link', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel_id', sa.String(), server_default=sa.text('NULL'), nullable=False),
    sa.Column('post_id', sa.String(), server_default='', nullable=False),
    sa.Column('pb_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('link', sa.String(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('channels')
    # ### end Alembic commands ###
